Repository AsyncCore/asynccore.github.io, pull requests merged in 2023-10, with the labels that each got.

#137 Muchos pequeños cambios.
  public/css/main-style.css
  public/index.html
  public/login-register.php
  public/main.php
  public/usuario-perfil.html
  src/form-validation.php
Labels: enhancement

#139 Añadidas constantes para cadenas y números mágicos y terminadas las
  public/css/Hilos-Posts.css
  public/css/index-style.css
  public/css/login-registro-style.css
  public/css/main-style.css
  public/login-register.php
  public/main.php
  src/form-validation.php
Labels: enhancement

#144 Mucho curro y pocas ganas de explicarlo. Léete la pull request.
  old/index2.html
  old/index3.html
  public/css/footer-style.css
  public/css/header-style.css
  public/css/index-style.css
  public/css/main-style.css
  public/error-pages/404.html
  public/footer.html
  public/header.html
  public/index.php
  public/main.php
  public/pruebas/PHP/index.php
  src/footer.php
  src/form-validation.php
  src/header.php
Labels: enhancement

#146 Ay las barritas :D
  src/form-validation.php
  src/header.php
Labels: bug

#147 En fin...
  src/form-validation.php
Labels: bug

#148 Arreglado el putito registro y además puesto con su header y su foote…
  public/css/login-registro-style.css
  public/login-register.php
  src/form-validation.php
Labels: bug

#149 Working daniel
  src/form-validation.php
Labels: bug

#158 Añadido E-R de la bbdd
  db/entidad-relacion.drawio
Labels: documentation

#160 Vamos con el push gordo!!!
  public/css/error-pages.css
  public/css/usuario-perfil-ajustes.css
  public/css/usuario-perfil-style.css
  public/error-pages/403.php
  public/error-pages/404.php
  public/error-pages/500.php
  public/error-pages/prism.css
  public/error-pages/prism.js
  public/js/error-pages.js
  public/main.php
  public/usuario-perfil-ajustes.php
  src/header.php
  templates/styles.css
Labels: enhancement

#161 Última hora!!! :D!
  public/css/index-style.css
Labels: bug
